version: '3.9'

networks:
  my_custom_network:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    # TODO: change to a volume
    volumes:
      - "C:/Users/droid/Desktop/Projects/django-project/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - my_custom_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_custom_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - my_custom_network

  web:
    build: .
    command: >
      sh -c "./scripts/wait-for-it.sh db:5432 -- python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - pgadmin
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - my_custom_network

  celery:
    build: .
    command: celery -A llm_eval worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      # TODO: ADD RESEND_API_KEY
      - RESEND_API_KEY=<RESEND_API_KEY>
    networks:
      - my_custom_network

